name: Go Release

on:
  push:
    tags:
      - 'v*'  # triggers on version tags like v0.1.0, v1.2.3

permissions:
    contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y libx11-dev

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Download Dependencies
        run: go mod tidy

      - name: Build Binary
        run: |
          echo "Building gh-oss-stats ..."
          mkdir -p dist
          GOOS=linux  GOARCH=amd64  go build -o dist/gh-oss-stats-linux-amd64   ./cmd/gh-oss-stats/main.go
          GOOS=linux  GOARCH=arm64  go build -o dist/gh-oss-stats-linux-arm64   ./cmd/gh-oss-stats/main.go
          GOOS=darwin GOARCH=arm64  go build -o dist/gh-oss-stats-darwin-arm64  ./cmd/gh-oss-stats/main.go

      - name: Trigger pkg.go.dev indexing
        run: |
          REPO="${{ github.repository }}"
          REPO_LOWER=$(echo "$REPO" | tr '[:upper:]' '[:lower:]')
          curl -X GET "https://proxy.golang.org/github.com/$REPO_LOWER/@v/${{ github.ref_name }}.info"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body_path: docs/release-notes/${{ github.ref_name }}.md
          generate_release_notes: false
          files: dist/*




